CLASSES = [0, 1, 2, 3, 4, 5]

TAMANHO_IMAGEM = 28
QUANTIDADE_FILTROS = 4
TAMANHO_FILTRO = 3
TAMANHO_POOLING = 2

TAXA_APRENDIZADO = 0.01
EPOCAS = 15

LIMITE_TREINO_POR_CLASSE = 180
LIMITE_TESTE_POR_CLASSE = 30

SEMENTE_ALEATORIA = 42

NOME_ARQUIVO_PESOS = "pesos.json"
